apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "content-studio.fullname" . }}-server
  labels:
    {{- include "content-studio.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  {{- if not .Values.autoscaling.server.enabled }}
  replicas: {{ .Values.server.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "content-studio.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "content-studio.server.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.secrets.create }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "content-studio.serviceAccountName" . }}
      containers:
        - name: server
          image: {{ include "content-studio.server.image" . }}
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          args: ["--mode=server"]
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "content-studio.fullname" . }}-config
            - secretRef:
                name: {{ include "content-studio.secretName" . }}
          env:
            - name: MODE
              value: "server"
            - name: REDIS_URL
              value: {{ include "content-studio.redisUrl" . }}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
